const WORDS = [
  'Able', 'Acid', 'Acorn', 'Active', 'Agile', 'Alert', 'Alley', 'Alpha', 'Amber', 'Angel',
  'Angry', 'Ankle', 'Apple', 'April', 'Arch', 'Arctic', 'Arena', 'Argon', 'Arm', 'Army',
  'Aroma', 'Arrow', 'Artic', 'Ash', 'Aspen', 'Aster', 'Atom', 'August', 'Aura', 'Auto',
  'Autumn', 'Azure', 'Baby', 'Badge', 'Bagel', 'Baker', 'Ball', 'Ballet', 'Bamboo', 'Banana',
  'Band', 'Banjo', 'Bank', 'Barn', 'Basil', 'Basin', 'Basket', 'Bass', 'Bat', 'Bath',
  'Bay', 'Beach', 'Bead', 'Bean', 'Bear', 'Beast', 'Beaver', 'Bee', 'Beetle', 'Bell',
  'Belly', 'Berry', 'Beta', 'Bike', 'Bird', 'Bison', 'Bitter', 'Black', 'Blade', 'Blaze',
  'Blend', 'Bless', 'Blink', 'Bliss', 'Block', 'Blonde', 'Bloom', 'Blossom', 'Blue', 'Bluff',
  'Blur', 'Board', 'Boat', 'Bold', 'Bolt', 'Bone', 'Bonus', 'Book', 'Boom', 'Boost',
  'Boot', 'Border', 'Born', 'Boss', 'Bottle', 'Bottom', 'Boulder', 'Bounce', 'Bound', 'Bow',
  'Bowl', 'Box', 'Boxer', 'Boy', 'Brain', 'Branch', 'Brass', 'Brave', 'Bread', 'Break',
  'Breeze', 'Brick', 'Bridge', 'Brief', 'Bright', 'Brisk', 'Broad', 'Bronze', 'Brook', 'Broom',
  'Brown', 'Brush', 'Buck', 'Bud', 'Buddy', 'Buffalo', 'Bug', 'Bulb', 'Bull', 'Bumble',
  'Bunny', 'Burst', 'Bush', 'Busy', 'Butler', 'Butter', 'Button', 'Cabin', 'Cable', 'Cactus',
  'Cake', 'Calm', 'Camel', 'Camera', 'Camp', 'Candle', 'Candy', 'Cane', 'Canoe', 'Canyon',
  'Cap', 'Cape', 'Card', 'Caret', 'Carpet', 'Carrot', 'Cart', 'Carve', 'Case', 'Cash',
  'Cast', 'Castle', 'Cat', 'Catch', 'Catnip', 'Cedar', 'Celery', 'Cell', 'Center', 'Chain',
  'Chair', 'Chalk', 'Charm', 'Chase', 'Cheer', 'Cheese', 'Cherry', 'Chess', 'Chest', 'Chicken',
  'Chief', 'Chili', 'Chime', 'Chip', 'Chirp', 'Chord', 'Chrome', 'Chunk', 'Circle', 'Citrus',
  'City', 'Civic', 'Clam', 'Clamp', 'Clarity', 'Classic', 'Claw', 'Clay', 'Clean', 'Clear',
  'Clever', 'Cliff', 'Climb', 'Clip', 'Cloak', 'Clock', 'Cloud', 'Clover', 'Clown', 'Club',
  'Clue', 'Coach', 'Coal', 'Coast', 'Coat', 'Cobalt', 'Cobra', 'Cocoa', 'Coconut', 'Code',
  'Coffee', 'Coil', 'Coin', 'Cold', 'Color', 'Colt', 'Comet', 'Compass', 'Cone', 'Conifer',
  'Cookie', 'Cool', 'Copper', 'Coral', 'Corn', 'Corner', 'Cosmic', 'Cotton', 'Couch', 'Country',
  'Court', 'Cove', 'Cozy', 'Crab', 'Crane', 'Crater', 'Crayon', 'Cream', 'Creek', 'Crest',
  'Crisp', 'Croco', 'Cross', 'Crown', 'Crust', 'Crystal', 'Cube', 'Cup', 'Curry', 'Curve',
  'Cyan', 'Cycle', 'Daffodil', 'Daily', 'Dairy', 'Daisy', 'Dance', 'Dandelion', 'Dart', 'Dash',
  'Dawn', 'Deer', 'Delight', 'Delta', 'Denim', 'Desert', 'Desk', 'Dew', 'Diamond', 'Dice',
  'Digit', 'Dill', 'Dingo', 'Direct', 'Disco', 'Disk', 'Diver', 'Dock', 'Doctor', 'Dodger',
  'Dog', 'Dolphin', 'Dome', 'Donut', 'Door', 'Dot', 'Double', 'Dove', 'Down', 'Dragon',
  'Draw', 'Dream', 'Dress', 'Drift', 'Drill', 'Drizzle', 'Drum', 'Duck', 'Dune', 'Dusk',
  'Dust', 'Duty', 'Eagle', 'Earl', 'Early', 'Earth', 'Easel', 'East', 'Easy', 'Eclipse',
  'Echo', 'Edge', 'Eel', 'Egg', 'Eight', 'Elbow', 'Elder', 'Elephant', 'Elf', 'Elk',
  'Elm', 'Ember', 'Emerald', 'Empire', 'Empty', 'Energy', 'Engine', 'Epic', 'Equal', 'Era',
  'Ermine', 'Essence', 'Ethereal', 'Ever', 'Exotic', 'Extra', 'Eye', 'Fable', 'Face', 'Fact',
  'Fair', 'Fairy', 'Falcon', 'Fall', 'Fame', 'Fan', 'Fancy', 'Fang', 'Fantasy', 'Far',
  'Farm', 'Fast', 'Fawn', 'Feather', 'Felt', 'Fern', 'Ferry', 'Fiber', 'Fiddle', 'Field',
  'Fiesta', 'Fig', 'Filet', 'Film', 'Final', 'Finch', 'Fine', 'Finish', 'Fire', 'Firefly',
  'Fish', 'Fist', 'Five', 'Fizz', 'Flag', 'Flake', 'Flame', 'Flamingo', 'Flannel', 'Flare',
  'Flash', 'Flask', 'Flax', 'Fleet', 'Flex', 'Flicker', 'Flight', 'Flint', 'Flip', 'Floc',
  'Floor', 'Flora', 'Flour', 'Flow', 'Flower', 'Flute', 'Fluffy', 'Fly', 'Foam', 'Fog',
  'Foil', 'Folk', 'Font', 'Food', 'Foot', 'Force', 'Forest', 'Fork', 'Fort', 'Forty',
  'Four', 'Fox', 'Frame', 'Fresh', 'Fringe', 'Frog', 'Frost', 'Frosty', 'Fruit', 'Full',
  'Fungus', 'Funk', 'Fur', 'Fuzzy', 'Gala', 'Galaxy', 'Gale', 'Game', 'Garden', 'Garlic',
  'Gaslit', 'Gate', 'Gazelle', 'Gem', 'Gentle', 'Ghost', 'Giant', 'Ginger', 'Giraffe', 'Girl',
  'Glacier', 'Glade', 'Glass', 'Gleam', 'Glide', 'Glimmer', 'Glitter', 'Globe', 'Gloom', 'Glow',
  'Glue', 'Goat', 'Goblet', 'Gold', 'Goldfish', 'Golf', 'Gondola', 'Goose', 'Gopher', 'Gorilla',
  'Gown', 'Grace', 'Grain', 'Grand', 'Grape', 'Graph', 'Grass', 'Gravel', 'Gravy', 'Gray',
  'Grease', 'Great', 'Green', 'Grid', 'Grill', 'Grin', 'Grip', 'Groove', 'Ground', 'Group',
  'Grove', 'Growl', 'Guava', 'Gull', 'Gum', 'Gust', 'Hail', 'Hair', 'Half', 'Hall',
  'Halo', 'Hammer', 'Hamster', 'Hand', 'Hang', 'Happy', 'Harbor', 'Hard', 'Hare', 'Harp',
  'Harvest', 'Hat', 'Hatch', 'Hawk', 'Hay', 'Haze', 'Hazel', 'Head', 'Heart', 'Heat',
  'Heavy', 'Hedge', 'Helm', 'Hemlock', 'Herb', 'Heron', 'Hex', 'Hickory', 'High', 'Hill',
  'Hint', 'Hippo', 'Hive', 'Hobby', 'Holly', 'Home', 'Honey', 'Hood', 'Hook', 'Hop',
  'Hope', 'Horizon', 'Horn', 'Horse', 'Host', 'Hot', 'Hotel', 'Hour', 'House', 'Hover',
  'Hue', 'Humble', 'Hunter', 'Husky', 'Ice', 'Icicle', 'Icon', 'Igloo', 'Image', 'Index',
  'India', 'Indigo', 'Inland', 'Inner', 'Iris', 'Iron', 'Island', 'Ivory', 'Ivy', 'Jade',
  'Jaguar', 'Jam', 'Jar', 'Jasmine', 'Jasper', 'Jazz', 'Jelly', 'Jet', 'Jewel', 'Jolly',
  'Joy', 'Judge', 'Juice', 'July', 'Jumbo', 'June', 'Jungle', 'Juniper', 'Jupiter', 'Jury',
  'Kale', 'Kayak', 'Keen', 'Kelp', 'Kettle', 'Key', 'Khaki', 'Kiln', 'Kind', 'King',
  'Kite', 'Kitten', 'Kiwi', 'Knight', 'Knot', 'Koala', 'Lab', 'Labyrinth', 'Lace', 'Ladder',
  'Lady', 'Lake', 'Lamb', 'Lamp', 'Lance', 'Land', 'Lane', 'Lantern', 'Lark', 'Laser',
  'Lava', 'Lavender', 'Lawn', 'Layer', 'Lazy', 'Leaf', 'Leap', 'Ledger', 'Left', 'Legend',
  'Lemon', 'Lens', 'Leopard', 'Level', 'Lever', 'Library', 'Light', 'Lilac', 'Lily', 'Lime',
  'Line', 'Linen', 'Lion', 'Lip', 'Liquid', 'Little', 'Lively', 'Llama', 'Loaf', 'Loam',
  'Lobster', 'Local', 'Lodge', 'Log', 'Lone', 'Long', 'Loop', 'Lotus', 'Loud', 'Lounge',
  'Love', 'Low', 'Loyal', 'Luck', 'Lucky', 'Lumber', 'Luna', 'Lunar', 'Lunch', 'Lush',
  'Lynx', 'Magic', 'Magnet', 'Magnolia', 'Mahogany', 'Mail', 'Main', 'Major', 'Mallow', 'Mango',
  'Maple', 'Marble', 'March', 'Mare', 'Marigold', 'Market', 'Marmot', 'Mars', 'Marsh', 'Mask',
  'Mast', 'Master', 'Matcha', 'Matte', 'Mauve', 'Meadow', 'Medal', 'Melon', 'Melt', 'Merit',
  'Mesa', 'Metal', 'Meteor', 'Meter', 'Mighty', 'Milk', 'Mimic', 'Mind', 'Mineral', 'Mint',
  'Mirror', 'Mist', 'Mocha', 'Mode', 'Modern', 'Mole', 'Mom', 'Monarch', 'Monkey', 'Moon',
  'Moose', 'Morning', 'Moss', 'Moth', 'Motor', 'Mount', 'Mouse', 'Muffin', 'Mule', 'Muse',
  'Music', 'Mystic', 'Nacho', 'Nacre', 'Nail', 'Name', 'Nap', 'Nation', 'Nature', 'Navy',
  'Nebula', 'Nectar', 'Needle', 'Neon', 'Nest', 'Net', 'Nettle', 'Nexus', 'Nibble', 'Nice',
  'Night', 'Nine', 'Noble', 'Nomad', 'Noon', 'North', 'Nose', 'Note', 'Nova', 'Nugget',
  'Numb', 'Nurse', 'Nut', 'Oak', 'Oasis', 'Oat', 'Ocean', 'Octave', 'Octopus', 'Odyssey',
  'Offer', 'Ogre', 'Oil', 'Okra', 'Olive', 'Omega', 'Onion', 'Onyx', 'Opal', 'Open',
  'Opera', 'Orange', 'Orbit', 'Orca', 'Orchid', 'Oriole', 'Osprey', 'Otter', 'Oval', 'Oven',
  'Owl', 'Ox', 'Oxygen', 'Oyster', 'Ozone', 'Pace', 'Pack', 'Page', 'Paint', 'Pair',
  'Palace', 'Pale', 'Palm', 'Panda', 'Panel', 'Pansy', 'Papaya', 'Paper', 'Parade', 'Park',
  'Parrot', 'Parsley', 'Party', 'Passion', 'Pasta', 'Patch', 'Path', 'Paw', 'Peace', 'Peach',
  'Peacock', 'Peak', 'Pear', 'Pearl', 'Pebble', 'Pecan', 'Pedal', 'Pelican', 'Pen', 'Penguin',
  'Penny', 'Pepper', 'Perch', 'Petal', 'Phase', 'Phoenix', 'Piano', 'Pickle', 'Pie', 'Pier',
  'Pigeon', 'Pillar', 'Pilot', 'Pine', 'Ping', 'Pink', 'Pioneer', 'Pipe', 'Pirate', 'Pistachio',
  'Pit', 'Pivot', 'Pixel', 'Pixie', 'Pizza', 'Plain', 'Planet', 'Plank', 'Plant', 'Plaster',
  'Plate', 'Plato', 'Play', 'Plaza', 'Plum', 'Plume', 'Plush', 'Pocket', 'Pod', 'Poem',
  'Point', 'Polar', 'Pole', 'Pond', 'Pony', 'Poodle', 'Pop', 'Poppy', 'Porch', 'Portal',
  'Post', 'Potato', 'Power', 'Prairie', 'Prawn', 'Press', 'Pretty', 'Pride', 'Primal', 'Prism',
  'Prize', 'Proof', 'Proper', 'Proud', 'Proxy', 'Prune', 'Puffin', 'Pug', 'Pulse', 'Puma',
  'Pump', 'Pumpkin', 'Punk', 'Pup', 'Puppy', 'Purity', 'Purple', 'Puzzle', 'Python', 'Quail',
  'Quake', 'Quark', 'Quartz', 'Queen', 'Quest', 'Quick', 'Quiet', 'Quill', 'Quilt', 'Quince',
  'Quiver', 'Rabbit', 'Raccoon', 'Race', 'Radar', 'Radio', 'Radish', 'Raft', 'Rain', 'Rainbow',
  'Raisin', 'Ram', 'Ranch', 'Range', 'Ranger', 'Rapid', 'Raspberry', 'Raven', 'Ray', 'Realm',
  'Red', 'Reed', 'Reef', 'Regal', 'Relay', 'Relish', 'Retro', 'Rhino', 'Rhubarb', 'Rice',
  'Rich', 'Ridge', 'Riff', 'Rifle', 'Right', 'Ring', 'Rise', 'River', 'Roam', 'Road',
  'Robin', 'Robot', 'Rock', 'Rocket', 'Rodeo', 'Rogue', 'Rook', 'Room', 'Root', 'Rope',
  'Rose', 'Rosy', 'Round', 'Route', 'Royal', 'Ruby', 'Rudder', 'Rug', 'Rune', 'Rush',
  'Rust', 'Rustic', 'Rye', 'Saber', 'Saddle', 'Safari', 'Saffron', 'Sage', 'Sail', 'Salad',
  'Salmon', 'Salt', 'Samba', 'Sand', 'Sapphire', 'Sashimi', 'Satin', 'Sauce', 'Savage', 'Savor',
  'Scarf', 'Scent', 'School', 'Scout', 'Seal', 'Season', 'Seed', 'Selfie', 'Sepia', 'Serene',
  'Shade', 'Shadow', 'Shake', 'Shallow', 'Shamrock', 'Shark', 'Sheep', 'Shell', 'Shelter', 'Shield',
  'Shimmer', 'Shine', 'Ship', 'Shiny', 'Shore', 'Short', 'Shore', 'Shrub', 'Sierra', 'Silk',
  'Silver', 'Simple', 'Sing', 'Siren', 'Sixty', 'Skate', 'Ski', 'Skull', 'Sky', 'Slate',
  'Sled', 'Sleek', 'Slick', 'Slide', 'Slim', 'Slope', 'Sloth', 'Small', 'Smart', 'Smile',
  'Smoke', 'Snail', 'Snake', 'Snap', 'Snipe', 'Snow', 'Soap', 'Soccer', 'Socks', 'Soda',
  'Soft', 'Solar', 'Solid', 'Song', 'Sonic', 'Sour', 'South', 'Space', 'Spark', 'Sparrow',
  'Speckle', 'Spicy', 'Spider', 'Spike', 'Spiral', 'Spirit', 'Splash', 'Spoon', 'Sport', 'Spot',
  'Spring', 'Spruce', 'Spur', 'Square', 'Squirrel', 'Stack', 'Stage', 'Stamp', 'Star', 'Starling',
  'Steam', 'Steel', 'Stem', 'Steppe', 'Stick', 'Stone', 'Stork', 'Storm', 'Story', 'Straw',
  'Stream', 'Street', 'Strike', 'Strong', 'Studio', 'Sturdy', 'Sugar', 'Summer', 'Sun', 'Sundae',
  'Sunny', 'Sunset', 'Super', 'Surf', 'Swan', 'Sweet', 'Swift', 'Sword', 'Sycamore', 'Syrup',
  'Table', 'Tacit', 'Taco', 'Tadpole', 'Tag', 'Tail', 'Taiga', 'Tall', 'Tamarind', 'Tame',
  'Tan', 'Tangerine', 'Tango', 'Tarot', 'Tart', 'Tasty', 'Teal', 'Teapot', 'Tempest', 'Tender',
  'Terra', 'Thicket', 'Thimble', 'Thistle', 'Thorn', 'Three', 'Throne', 'Thunder', 'Tidal', 'Tide',
  'Tiger', 'Timber', 'Time', 'Tin', 'Tiny', 'Tip', 'Toad', 'Toast', 'Toffee', 'Token',
  'Tomato', 'Top', 'Topaz', 'Torch', 'Tornado', 'Tortoise', 'Total', 'Toucan', 'Tour', 'Tower',
  'Town', 'Toy', 'Trace', 'Track', 'Trade', 'Trail', 'Train', 'Treat', 'Tree', 'Tribe',
  'Trick', 'Tropic', 'Trout', 'Truck', 'True', 'Trumpet', 'Truffle', 'Trunk', 'Trust', 'Tulip',
  'Tuna', 'Tundra', 'Turkey', 'Turnip', 'Turtle', 'Twig', 'Twilight', 'Twist', 'Umbra', 'Umbrella',
  'Unicorn', 'Urban', 'Urchin', 'Valley', 'Vanilla', 'Velvet', 'Venom', 'Venus', 'Verdant', 'Vessel',
  'Vibrant', 'Victor', 'Viking', 'Vine', 'Violet', 'Violin', 'Viper', 'Virtue', 'Visor', 'Vista',
  'Volcano', 'Vole', 'Voyage', 'Wagon', 'Walnut', 'Walrus', 'Wand', 'Warm', 'Wasabi', 'Watch',
  'Water', 'Wave', 'Wax', 'Weasel', 'Weave', 'Web', 'West', 'Whale', 'Wheat', 'Whisk',
  'Whisker', 'Whisper', 'White', 'Wild', 'Willow', 'Wind', 'Window', 'Wine', 'Wing', 'Winter',
  'Wire', 'Wise', 'Wisp', 'Wolf', 'Wombat', 'Wonder', 'Wood', 'Wool', 'Worm', 'Wrap',
  'Wreath', 'Xenon', 'Xylophone', 'Yacht', 'Yak', 'Yarn', 'Yellow', 'Yeti', 'Yew', 'Yoga',
  'Yogurt', 'Young', 'Zebra', 'Zen', 'Zephyr', 'Zest', 'Zigzag', 'Zinc', 'Zinnia', 'Zodiac',
];

function pickRandom() {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}

export function randomGameName() {
  const first = pickRandom();
  let second = pickRandom();
  while (second === first) second = pickRandom();
  let third = pickRandom();
  while (third === first || third === second) third = pickRandom();
  return `${first} ${second} ${third}`;
}

export const WORD_COUNT = WORDS.length;
